### ISSUE TITLE
Buttons not moving inside MMBF frame

### ISSUE THREAD

**Issue by FrostShock** [laytya/MinimapButtonFrame-vanilla#10]
I just tried a few more addons and the following addons minimap buttons do not move inside the MinimapButtonFrame window

* ActionBarProfiles   -   https://github.com/firenahzku/ActionBarProfiles
* CT_MasterMod   -   http://www.vanilla-addons.com/dls/ctmod/%C2%A0
* CallToArms   -   https://github.com/Road-block/CallToArms

<a href="https://imgur.com/nuzaQ4P"><img src="https://i.imgur.com/nuzaQ4P.jpg" title="source: imgur.com" /></a>

**Comment by laytya** [comment]
You can always add unsupported icons by /mbf add commant hovering icon
